### PR TITLE
Fix cmake object libraries in static build

### PR DESCRIPTION
**Pull request by JoniSt**
Hi again,

SAIL's static build was sadly broken for me since commit ce0e3d2824936013083fdc8219a1f3916cc3ebbc. SAIL could still be built statically but the ```sail-codecs-objects``` archive produced by the build didn't contain the private ```bmp-common``` library that's shared by the BMP and ICO codecs. That meant linking with SAIL failed because the symbols from ```bmp-common``` were missing.

I've tried to fix this by making common libraries like ```bmp-common``` build as object libraries as well, just like the codecs themselves. This fixes the static build for me.

I'm not sure if I broke other things in the process though so I'd be quite happy if you could review my changes when you have time!

### CODE REVIEW

**Comment by HappySeaFox** [comment]
Hi! Thanks for the pr.

What's your OS, compiler, and the cmake command line? The issue is very suspicious. SAIL is successfully used by the static vcpkg builds.

**Comment by JoniSt** [comment]
It's Debian Testing (bookworm), GCC 11.2, and I define the following cmake options:
```
                    "-DSAIL_BUILD_EXAMPLES:BOOL=OFF"
                    "-DSAIL_BUILD_TESTS:BOOL=OFF"
                    "-DSAIL_COLORED_OUTPUT:BOOL=OFF"
                    "-DSAIL_STATIC:BOOL=ON"
                    "-DSAIL_ONLY_CODECS:STRING=png|jpeg|bmp"
                    "-DSAIL_THIRD_PARTY_CODECS_PATH:BOOL=OFF"
```

The exact issue lies here:
```
# src/sail-codecs-archive/CMakeLists.txt

    # Link all the enabled codecs dependencies into sail-codecs
    #
    foreach(codec ${ENABLED_CODECS})
        get_target_property(CODEC_LINK_LIBRARIES sail-codec-${codec} LINK_LIBRARIES)
        target_link_libraries(sail-codecs PRIVATE ${CODEC_LINK_LIBRARIES})
    endforeach()
```
The bmp codec depends on bmp-common, so bmp-common ends up being linked to sail-codecs in this foreach loop. However, this means that it is left as a separate file and sail-codecs.a points to bmp-common.a. (The ```--whole-archive``` library copying trick also doesn't work reliably as evidenced by the fact that you're currently installing sail-codecs-objects as well even though it should've been copied into sail-codecs.)

All of the codecs already turn into object libraries in a combined codec build, which means that their source files are just directly compiled into the sail-codecs archive. bmp-common should therefore be an object library too when combining codecs; only external dependencies should be linked to sail-codecs with ```target_link_libraries```. That makes the whole build more consistent: When building separate codec binaries, everything is linked via static libs. When building combined codecs, all codec source files are thrown together and compiled into a single library, including the common stuff.

This also makes it possible to get rid of this "library copying" stuff with ```--whole-archive``` since no static libraries have to be copied into sail-codecs; it is instead fully built from source files.

**Comment by HappySeaFox** [comment]
I see, thanks! I'll look into this more.

**Comment by HappySeaFox** [comment]
After investigating the issue, I have the following proposal in mind. Since I statically link common codecs into every codec where they're needed, I can achieve the same with make the common codec OBJECT library instead of STATIC. This way we can easily link against common codecs with `target_link_libraries` when SAIL_STATIC is OFF, and pull these OBJECT dependencies when SAIL_STATIC is ON.

Could you please test the attached patch (rename to .diff or .patch and `git apply` it)? It works fine on my Windows and Linux installation. it's not final. I'm thinking about a recursive search for OBJECT dependencies.

[common-codecs-as-object-libs.txt](https://github.com/HappySeaFox/sail/files/7965042/common-codecs-as-object-libs.txt)

**Comment by JoniSt** [comment]
I'm not quite sure that this patch will work on every platform - you still need the common codecs to be STATIC when you build the codecs as separate dynamic libraries. (That's because linking against an object library with ```target_link_libraries``` doesn't work since there's no archive to link.) That's why I introduced the ```sail_codec_common``` macro in my PR: It creates a STATIC library for the common codec when building the codecs separately and an OBJECT library when the codecs will be combined.

You're also currently missing a call to ```list(REMOVE_DUPLICATE ...)``` to deduplicate the list of object libraries. This is critical because otherwise cmake will compile and link the common source files multiple times, leading to duplicate symbols. (OBJECT libraries are just lists of source files, if you don't deduplicate them, you'll specify the same source file multiple times.)

If you implement these changes, you'll basically arrive at the code in this pull request.

The only additional change I made is that I removed ```sail-codecs-objects``` because that library is redundant when all codec source files are compiled directly into the sail-codecs library. (At least I think so. Why did you introduce sail-codecs-objects in the first place? Right now the code around it seems a little weird to me, it gets built only to be integrated into sail-codecs.)

I'm also not quite sure if the recursive search is required. Object libraries should propagate their dependencies.

**Comment by HappySeaFox** [comment]
>That's because linking against an object library with target_link_libraries doesn't work since there's no archive to link - it's a no-op

The main idea behind my patch is to implement the simplest fix. And the magic here is that linking against object libs works similar to linking against STATIC common codecs. Ref: https://cmake.org/cmake/help/latest/command/target_link_libraries.html#linking-object-libraries `Normal libraries and executables may link to Object Libraries to get their objects and usage requirements. Continuing the above example, the code`.

The patch is not ready yet, but the main idea is already there. Not sure if we need to have `sail_codec_common` for now, as common-bmp is currently the only place where we used it. Also, we don't use complex configuration to add a common codec, just `add_library`.

>You're also currently missing a call to list(REMOVE_DUPLICATE ...) to deduplicate the list of object libraries

Sure, totally true :+1: 

>The only additional change I made is that I removed sail-codecs-objects because that library is redundant when all codec source files are compiled directly into the sail-codecs library

Agree, it looks over-complicated. But this is the only I found that works on all platforms. Since I don't refer to symbols in codecs via linker, a compiler is totally free to throw them away. That's why I force compiler to include the codecs symbols into the final linking command line with `whole-arhive`. Why not to use a single sail-codec-objects then? Good question, not sure if I remember the reason behind that :smile: 

>I'm also not quite sure if the recursive search is required. Object libraries should propagate their dependencies.

For static builds, we add a static library `sail-codec-objects` with real codecs objects. Propagation doesn't work here. We need to specify the exact list of objects to add into `sail-codec-objects` with all their dependencies.

Thanks for your great ideas :+1: :+1:

**Comment by JoniSt** [comment]
You're right, I must've missed that in CMake's documentation! Then the solution is even simpler. I just did that change in my fork. It does however mean that common libraries can't depend on other common libraries (because ```target_link_libraries``` only includes the objects from the immediately specified libraries and not those of transitive dependencies).

One more thing that came to my mind: You also have to separate object libraries from regular libraries. When you add an object library in ```add_library(sail-common /* ob lib here */)```, you may not also link against it using ```target_link_libraries``` because then you'd get duplicate symbol definitions again. I think the code in this PR should do this correctly.

**Comment by HappySeaFox** [comment]
Maybe I can take the responsibility over the final patch and we can review it together in a different PR.

**Comment by JoniSt** [comment]
Of course! :+1:

**Comment by HappySeaFox** [comment]
>It does however mean that common libraries can't depend on other common libraries (because target_link_libraries only includes the objects from the immediately specified libraries and not those of transitive dependencies)

Yeah, and I truly hope we will not need such a complex mechanism :smile:

**Pull request closed without merging**
